version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - composer install
  build:
    commands:
      - composer build-docs

artifacts:
  files:
    - './**/*'
  base-directory: './doc'

cache:
  paths:
    - '/root/.composer/**/*'