<?php
declare(strict_types = 1);

namespace Wambo\Demo;

use Exception;
use Wambo\Demo\Core\App;
use Wambo\Demo\Demo\Registration as DemoRegistration;

error_reporting(E_ALL ^ E_DEPRECATED ^ E_NOTICE);
ini_set('display_errors', '1');

// define root directory for the project
define('API_ROOT_DIR', dirname(getcwd() . '..'));

// load autoload file generated by composer
$autoload_filename = API_ROOT_DIR . '/vendor/autoload.php';
if (!file_exists($autoload_filename)) {
    header("Not Found", true, 404);
    echo $autoload_filename . " was not found";
    die;
}

require_once $autoload_filename;

$app = new App();
$app->registerPackage(new DemoRegistration());
try {
    $app->run();
} catch (Exception $e) {
    echo 'error';
}
